"""Split definition builder for RADS evaluation.

Builds the held-out PICEK evaluation split as explicit same-source
positive/negative pairs, and can regenerate the P02 test split from its
metadata CSV.

Paths are derived from this file's location, so the script is portable across
checkouts. Emitted `processed_path` values are repository-root relative and
begin with `Datasets/`, which is the prefix `rads/evaluation/evaluator.py`
resolves by joining onto the repository root.
"""

from __future__ import annotations

import argparse
import os
import random
import re
from collections import defaultdict
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = REPO_ROOT / "rads" / "config"

POSITIVE_REL_DIR = "Datasets/processed/picek_sorted/trimmed/positive/real"
NEGATIVE_REL_DIR = "Datasets/processed/picek_sorted/trimmed/negative/real"
P02_METADATA_REL = "Datasets/processed/picek/p02_binary/picek_p02_binary_metadata.csv"

DEFAULT_HELDOUT_OUTPUT = CONFIG_DIR / "picek_heldout_split_v2.csv"
DEFAULT_P02_OUTPUT = CONFIG_DIR / "p02_test_split_v2.csv"
P02_REFERENCE_SPLIT = CONFIG_DIR / "p02_test_split.csv"

# Evidence of the prior evaluation run. Never regenerated by this script.
PROTECTED_OUTPUTS = {"picek_500_split.csv", "p02_test_split.csv"}

TARGET_PAIRS = 250
SEED = 42
LEGACY_SKIP_PER_CLASS = 30

# Sources used to tune reasoning and severity thresholds during Phases 1-7.
# Named in docs/NEW.md and in the two experiment directories under
# rads/evaluation/experiments/.
TUNING_SOURCES = (
    "-6SQSDj8cYU",
    "-dmYsQc-odI",
    "-2UPLUV7JLg",
    "-9oifpjUxxM",
    "-7-vQ4obVwQ",
    "-AztVDZ6cEE",
    "-FQxK6HdxNU",
    "-NgnSm_oEB4",
    "-PpBteU0p3Q",
    "-PpjzmhI_PE",
    "-Qt5bDJNT84",
    "-RE3XseZINA",
    "-RrDtLjWsT4",
    "-SNFUobKjoM",
)

_VARIANT_SUFFIX = re.compile(r"_\d{2}$")
_CLIP_INDEX_SUFFIX = re.compile(r"_\d+$")


def extract_source_id(filename: str) -> str:
    """Return the source video id for a processed clip filename.

    Processed clip names follow `<source>[_<clip index>]_<2-digit variant>.mp4`.
    Both numeric suffixes are removed; anything else is left intact, so source
    ids that themselves end in digits (`russia23`, `video13`) survive.
    """
    stem = os.path.splitext(os.path.basename(filename))[0]
    stem = _VARIANT_SUFFIX.sub("", stem, count=1)
    stem = _CLIP_INDEX_SUFFIX.sub("", stem, count=1)
    return stem


def list_clips(directory: Path) -> list[str]:
    if not directory.is_dir():
        raise FileNotFoundError(f"Clip directory not found: {directory}")
    return sorted(f for f in os.listdir(directory) if f.lower().endswith(".mp4"))


def legacy_skip_sources(pos_files: list[str], neg_files: list[str], n: int) -> set[str]:
    """Sources covered by the original script's first-N-sorted-files-per-class skip."""
    skipped: set[str] = set()
    for files in (pos_files, neg_files):
        for name in files[:n]:
            skipped.add(extract_source_id(name))
    return skipped


def p02_sources() -> set[str]:
    if not P02_REFERENCE_SPLIT.is_file():
        return set()
    df = pd.read_csv(P02_REFERENCE_SPLIT)
    column = "source_video_id" if "source_video_id" in df.columns else "video_id"
    return {extract_source_id(str(v)) for v in df[column]}


def build_heldout_split(target_pairs: int = TARGET_PAIRS, seed: int = SEED) -> tuple[pd.DataFrame, dict]:
    pos_dir = REPO_ROOT / POSITIVE_REL_DIR
    neg_dir = REPO_ROOT / NEGATIVE_REL_DIR

    pos_files = list_clips(pos_dir)
    neg_files = list_clips(neg_dir)

    pos_sources = {extract_source_id(f) for f in pos_files}
    neg_sources = {extract_source_id(f) for f in neg_files}

    # A pair is the same clip basename present in both class directories, which
    # is the correspondence the P02 split uses (positive_accident and
    # negative_pre_accident trimmed from one source video).
    pos_set = set(pos_files)
    paired_names = sorted(name for name in neg_files if name in pos_set)

    by_source: dict[str, list[str]] = defaultdict(list)
    for name in paired_names:
        by_source[extract_source_id(name)].append(name)

    pairable_sources = set(by_source)
    tuning = set(TUNING_SOURCES)
    legacy = legacy_skip_sources(pos_files, neg_files, LEGACY_SKIP_PER_CLASS)
    excluded = tuning | legacy

    eligible = sorted(pairable_sources - excluded)
    rng = random.Random(seed)
    rng.shuffle(eligible)
    chosen = sorted(eligible[:target_pairs])

    records = []
    for source in chosen:
        basename = sorted(by_source[source])[0]
        stem = os.path.splitext(basename)[0]
        records.append(
            {
                "video_id": f"picek_pos_{stem}",
                "source_video_id": source,
                "binary_label": 1,
                "clip_role": "positive_accident",
                "processed_path": f"{POSITIVE_REL_DIR}/{basename}",
                "split_in_distribution": "test",
            }
        )
        records.append(
            {
                "video_id": f"picek_neg_{stem}",
                "source_video_id": source,
                "binary_label": 0,
                "clip_role": "negative_pre_accident",
                "processed_path": f"{NEGATIVE_REL_DIR}/{basename}",
                "split_in_distribution": "test",
            }
        )

    df = pd.DataFrame(records)

    missing = [p for p in df["processed_path"] if not (REPO_ROOT / p).is_file()]
    overlap_p02 = sorted(set(chosen) & p02_sources())

    stats = {
        "positive_clips": len(pos_files),
        "negative_clips": len(neg_files),
        "positive_sources": len(pos_sources),
        "negative_sources": len(neg_sources),
        "all_sources": len(pos_sources | neg_sources),
        "sources_in_both_classes": len(pos_sources & neg_sources),
        "pairable_sources": len(pairable_sources),
        "pairable_sources_multi_pair": sum(1 for v in by_source.values() if len(v) > 1),
        "tuning_sources_listed": len(tuning),
        "tuning_sources_excluded_from_pairable": len(tuning & pairable_sources),
        "legacy_skip_sources_excluded_from_pairable": len(legacy & pairable_sources),
        "total_sources_excluded_from_pairable": len(excluded & pairable_sources),
        "eligible_pairs": len(eligible),
        "target_pairs": target_pairs,
        "selected_pairs": len(chosen),
        "rows": len(df),
        "positives": int((df["binary_label"] == 1).sum()) if len(df) else 0,
        "negatives": int((df["binary_label"] == 0).sum()) if len(df) else 0,
        "duplicate_video_ids": int(len(df) - df["video_id"].nunique()) if len(df) else 0,
        "missing_files": len(missing),
        "p02_source_overlap": len(overlap_p02),
        "p02_overlap_sources": overlap_p02,
        "seed": seed,
    }
    return df, stats


def print_preflight(stats: dict) -> None:
    print("Pre-flight counts")
    print(f"  positive clip directory : {stats['positive_clips']} clips")
    print(f"  negative clip directory : {stats['negative_clips']} clips")
    print(f"  unique sources (positive dir) : {stats['positive_sources']}")
    print(f"  unique sources (negative dir) : {stats['negative_sources']}")
    print(f"  unique sources (both dirs)    : {stats['all_sources']}")
    print(f"  sources present in both classes : {stats['sources_in_both_classes']}")
    print(f"  pairable sources (same basename in both dirs) : {stats['pairable_sources']}")
    print(f"  pairable sources with more than one pair : {stats['pairable_sources_multi_pair']}")
    print(f"  tuning sources listed : {stats['tuning_sources_listed']}")
    print(f"  tuning sources removed from pairable pool : {stats['tuning_sources_excluded_from_pairable']}")
    print(f"  legacy first-{LEGACY_SKIP_PER_CLASS}-per-class sources removed from pairable pool : "
          f"{stats['legacy_skip_sources_excluded_from_pairable']}")
    print(f"  total sources removed from pairable pool : {stats['total_sources_excluded_from_pairable']}")
    print(f"  eligible pairs after exclusions : {stats['eligible_pairs']}")
    print(f"  target pairs : {stats['target_pairs']}")
    print(f"  selected pairs : {stats['selected_pairs']}")
    print(f"  rows : {stats['rows']} (positives {stats['positives']}, negatives {stats['negatives']})")
    print(f"  duplicate video_id : {stats['duplicate_video_ids']}")
    print(f"  processed_path entries missing on disk : {stats['missing_files']}")
    print(f"  selected sources also present in p02_test_split.csv : {stats['p02_source_overlap']}")
    if stats["selected_pairs"] < stats["target_pairs"]:
        print(f"  NOTE: only {stats['selected_pairs']} pairs exist after exclusions; "
              f"the split is balanced at that smaller size rather than padded.")


def check_output_path(path: Path) -> None:
    if path.name in PROTECTED_OUTPUTS:
        raise ValueError(
            f"{path.name} is prior-run evidence and must not be regenerated. "
            f"Choose a different --output."
        )


def create_heldout_split(output: Path, target_pairs: int, seed: int, dry_run: bool) -> dict:
    check_output_path(output)
    df, stats = build_heldout_split(target_pairs=target_pairs, seed=seed)
    print_preflight(stats)

    if stats["missing_files"]:
        raise RuntimeError(f"{stats['missing_files']} processed_path entries do not exist on disk")
    if stats["duplicate_video_ids"]:
        raise RuntimeError(f"{stats['duplicate_video_ids']} duplicate video_id values")
    if stats["positives"] != stats["negatives"]:
        raise RuntimeError("class counts are not balanced")

    if dry_run:
        print("Dry run: no file written.")
        return stats

    output.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output, index=False)
    print(f"Wrote {output} with {len(df)} rows.")
    return stats


def create_p02_test_split(output: Path) -> None:
    check_output_path(output)
    metadata = REPO_ROOT / P02_METADATA_REL
    df = pd.read_csv(metadata)
    test_df = df[df["split_in_distribution"] == "test"].copy()
    print(f"Found {len(test_df)} test samples in P02 metadata.")
    output.parent.mkdir(parents=True, exist_ok=True)
    test_df.to_csv(output, index=False)
    print(f"Wrote {output}.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build RADS evaluation split definitions")
    parser.add_argument("--output", type=Path, default=DEFAULT_HELDOUT_OUTPUT,
                        help="Output CSV for the held-out paired split")
    parser.add_argument("--target-pairs", type=int, default=TARGET_PAIRS)
    parser.add_argument("--seed", type=int, default=SEED)
    parser.add_argument("--dry-run", action="store_true",
                        help="Print pre-flight counts without writing the CSV")
    parser.add_argument("--p02", action="store_true",
                        help="Also regenerate the P02 test split from metadata")
    parser.add_argument("--p02-output", type=Path, default=DEFAULT_P02_OUTPUT)
    args = parser.parse_args()

    if args.p02:
        create_p02_test_split(args.p02_output)
    create_heldout_split(args.output, args.target_pairs, args.seed, args.dry_run)


if __name__ == "__main__":
    main()
